target_column: "booking status"
cutoff_date: "9/19/2018"

"to_feature_store": True
"feature_group_name": "booking_ingested"
"feature_group_version": 1

split_train_target_column: booking_status
split_train_date_column: date_of_reservation
split_train_ratio: 0.8
