hyperparameters : 
  LogisticRegression:
    C: [0.01, 0.1, 1, 10]
    penalty: ['l2', 'l1']
    solver: ['lbfgs', 'saga']
    random_state: [42]
  RandomForestClassifier:
    n_estimators: [100, 200]
    max_depth: [5, 10, 20]
    min_samples_split: [2, 5, 10]
    random_state: [42]
  XGBClassifier:
    n_estimators: [100, 200, 500]
    max_depth: [10, 20]
    learning_rate: [0.01, 0.1, 0.2]
    random_state: [42]