target_column: "booking status"
split_ratio: 0.75

preprocessing:
  drop_columns: ["car_parking_space", "repeated", "p_c", "p_not_c"]

"to_feature_store": False
"feature_group_name": "booking_ingested"
"feature_group_version": 1

"to_feature_store_preprocessed": False
"feature_group_name_preprocessed": "booking_train_preprocessed"
"feature_group_version_preprocessed": 1
split_train_target_column: booking_status
split_train_date_column: date_of_reservation
split_train_ratio: 0.8


use_grid_search: True
use_feature_selection: True
model_name: "hotel"
baseline_model_params:
  penalty: "l2"
  C: 1.0
  solver: "lbfgs"
  max_iter: 100
  random_state: 42

drift_detection:
  # Data settings
  reference_data_path: "data/03_primary/X_train_trees.csv"
  timestamp_column: 'date_of_reservation'
  chunk_size: 1500  # ~6 chunks for analysis data (8943/1500 ≈ 6)
  
  # Feature selection - use all features from model training
  use_all_model_features: true
  
  # Detection methods by feature type
  categorical_methods: ['chi2']  # For binary features
  continuous_methods: ['jensen_shannon']  # For float features  
  discrete_methods: ['chi2']  # For int features (treat as categorical)
  
  # Alert settings
  alert_threshold: 0.05
  save_plots: true
  plots_path: "data/08_reporting/"