target_column: "booking status"
cutoff_date: "9/19/2018"

preprocessing:
  drop_columns: ["car_parking_space", "repeated", "p_c", "p_not_c"]

"to_feature_store": False
"feature_group_name": "booking_ingested"
"feature_group_version": 1

split_train_target_column: booking_status
split_train_date_column: date_of_reservation
split_train_ratio: 0.8



use_feature_selection: False
model_name: "hotel"
baseline_model_params:
  penalty: "l2"
  C: 1.0
  solver: "lbfgs"
  max_iter: 100
  random_state: 42


use_grid_search: True