target_column: "booking status"
cutoff_date: "9/19/2018"

preprocessing:
  drop_columns: ["car_parking_space", "repeated", "p_c", "p_not_c"]

"to_feature_store": False
"feature_group_name": "booking_ingested"
"feature_group_version": 1

